package card

import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba4.axi._
import spinal.lib.bus.amba4.axilite._
import card.contract.Contract
import Contract.{Message, Map => M}

// S5: the guest's SoC around the host link, in one clock domain. VexiiRiscv's LiteX cluster (generated
// Verilog: cores, CLINT and PLIC at QEMU virt's addresses) reaches main memory through its AXI4 port and
// the devices through its AXI-lite port. Main memory is a port of 64-byte lines that the board's DDR3
// controller serves; the host link's copies share it while GUEST_RESET holds the cores (the boot
// window). The DMA and ring windows are block RAM until S6 puts channel B behind them.

/** VexiiRiscv's LiteX SoC (vexiiriscv.soc.litex.SocGen), generated by designs/soc-s5's prebuild. */
case class VexiiCluster(rtl: String) extends BlackBox {
  setDefinitionName("VexiiCluster")
  val litex_clk = in Bool ()
  val litex_reset = in Bool ()
  val peripheral_externalInterrupts_port = in Bits (32 bits)
  val mBus = master(Axi4(SocCore.mBusConfig))
  val pBus = master(AxiLite4(AxiLite4Config(32, 32)))
  val debug = out Bits (8 bits)
  val mBus_awallStrb = out Bool () // Vexii's hint that a write fills its whole line; unused
  Axi4SpecRenamer(mBus)
  AxiLite4SpecRenamer(pBus)
  addRTLPath(rtl)
}

object SocCore {
  val mBusConfig = Axi4Config(addressWidth = 32, dataWidth = 64, idWidth = 8, useRegion = false, useLock = false,
    useCache = false, useQos = false, useProt = false)
}

/** Requests from several masters onto one line port, round-robin, with up to `depth` in flight. The line
  * port answers in order, so a FIFO of who asked routes each response back to the master that made it. */
case class LineArbiter(n: Int, depth: Int = 8) extends Component {
  val io = new Bundle {
    val up = Vec(slave(Stream(MemCmd())), n)
    val upRsp = Vec(master(Stream(Bits(8 * Message.Size bits))), n)
    val down = master(Stream(MemCmd()))
    val downRsp = slave(Stream(Bits(8 * Message.Size bits)))
  }
  val arbiter = StreamArbiterFactory().roundRobin.noLock.build(MemCmd(), n)
  (arbiter.io.inputs, io.up).zipped.foreach(_ << _)
  val order = StreamFifo(UInt(log2Up(n) bits), depth)
  val (toDown, toOrder) = StreamFork2(arbiter.io.output, synchronous = true)
  io.down << toDown
  order.io.push << toOrder.translateWith(arbiter.io.chosen)
  val owner = order.io.pop.payload
  for ((r, i) <- io.upRsp.zipWithIndex) { r.valid := io.downRsp.valid && order.io.pop.valid && owner === i; r.payload := io.downRsp.payload }
  io.downRsp.ready := order.io.pop.valid && io.upRsp(owner).ready
  order.io.pop.ready := io.downRsp.fire
}

/** The cores' AXI4 memory port as 64-byte line accesses, with several in flight. Reads: bursts queue up,
  * an issuer sends a line read for every line each burst touches (as far ahead as there is room for the
  * answers), and a deliverer turns the answers, in order, into the bursts' beats. Writes: the beats of a
  * line gather into one masked line write; a burst's B response goes back once its last line write is
  * answered. INCR bursts of any size and alignment; responses in AXI order (the same as request order). */
case class Axi4ToLines(cfg: Axi4Config, base: BigInt, depth: Int = 4) extends Component {
  val io = new Bundle {
    val axi = slave(Axi4(cfg))
    val read = master(Stream(MemCmd()))
    val readRsp = slave(Stream(Bits(8 * Message.Size bits)))
    val write = master(Stream(MemCmd()))
    val writeRsp = slave(Stream(Bits(8 * Message.Size bits)))
  }
  private val lineBits = log2Up(Message.Size)
  private val wordBits = log2Up(cfg.bytePerWord)
  private val aw = cfg.addressWidth
  private def lineOf(a: UInt): UInt = (a.resize(64 bits) - base)(63 downto lineBits) @@ U(0, lineBits bits)
  private def lineIndex(a: UInt): UInt = a(aw - 1 downto lineBits)
  case class Burst() extends Bundle {
    val addr = UInt(aw bits)
    val len = UInt(8 bits)
    val size = UInt(3 bits)
    val id = UInt(cfg.idWidth bits)
    def last: UInt = addr + ((len.resize(aw bits) + 1) |<< size) - 1 // the burst's last byte
  }
  private def burstOf(a: Axi4Ax): Burst = { val b = Burst(); b.addr := a.addr; b.len := a.len; b.size := a.size; b.id := a.id; b }

  val rd = new Area {
    val bursts = io.axi.ar.translateWith(burstOf(io.axi.ar.payload)).queue(depth)
    val (toIssue, toDeliver) = StreamFork2(bursts)
    // the issuer: a line read for each line of the burst at its head
    val line = Reg(UInt(aw - lineBits bits))
    val started = Reg(Bool()) init False
    val inFlight = Reg(UInt(log2Up(depth + 1) bits)) init 0 // line reads not yet consumed by the deliverer
    val answers = StreamFifo(Bits(8 * Message.Size bits), depth)
    val cur = started ? line | lineIndex(toIssue.addr)
    val lastLine = lineIndex(toIssue.payload.last)
    io.read.valid := toIssue.valid && inFlight =/= depth
    io.read.payload.write := False
    io.read.payload.address := lineOf(cur @@ U(0, lineBits bits))
    io.read.payload.data := 0
    io.read.payload.mask := 0
    toIssue.ready := io.read.fire && cur === lastLine
    when(io.read.fire) { line := cur + 1; started := cur =/= lastLine }
    answers.io.push << io.readRsp
    // the deliverer: beats from the answers, in order
    val beats = toDeliver.queue(depth)
    val addr = Reg(UInt(aw bits))
    val left = Reg(UInt(8 bits))
    val busy = Reg(Bool()) init False
    val a = busy ? addr | beats.addr
    val l = busy ? left | beats.len
    val next = a + (U(1, aw bits) |<< beats.size)
    io.axi.r.valid := beats.valid && answers.io.pop.valid
    io.axi.r.data := answers.io.pop.payload.subdivideIn(cfg.dataWidth bits)(a(lineBits - 1 downto wordBits))
    io.axi.r.id := beats.id
    io.axi.r.resp := 0
    io.axi.r.last := l === 0
    val lineDone = l === 0 || lineIndex(next) =/= lineIndex(a)
    answers.io.pop.ready := io.axi.r.fire && lineDone
    beats.ready := io.axi.r.fire && l === 0
    when(io.axi.r.fire) { addr := next; left := l - 1; busy := l =/= 0 }
    inFlight := inFlight + U(io.read.fire) - U(answers.io.pop.fire)
  }

  val wr = new Area {
    val bursts = io.axi.aw.translateWith(burstOf(io.axi.aw.payload)).queue(depth)
    val addr = Reg(UInt(aw bits))
    val busy = Reg(Bool()) init False
    val data = Reg(Bits(8 * Message.Size bits))
    val mask = Reg(Bits(Message.Size bits)) init 0
    val a = busy ? addr | bursts.addr
    val next = a + (U(1, aw bits) |<< bursts.size)
    // a gathered line, waiting to go out; whether it ends its burst (and the burst's id)
    case class LineWrite() extends Bundle { val cmd = MemCmd(); val last = Bool(); val id = UInt(cfg.idWidth bits) }
    val out = Stream(LineWrite())
    val outQ = out.queue(2)
    io.axi.w.ready := bursts.valid && out.ready
    out.valid := False
    out.payload.cmd.write := True
    out.payload.cmd.address := lineOf(a)
    out.payload.cmd.data := data
    out.payload.cmd.mask := mask
    out.payload.last := io.axi.w.last
    out.payload.id := bursts.id
    bursts.ready := False
    when(io.axi.w.fire) {
      val word = a(lineBits - 1 downto wordBits)
      val d = Bits(8 * Message.Size bits); val m = Bits(Message.Size bits)
      d := data; m := mask
      for (k <- 0 until Message.Size / cfg.bytePerWord) when(word === k) {
        for (b <- 0 until cfg.bytePerWord) when(io.axi.w.strb(b)) {
          d(8 * (k * cfg.bytePerWord + b), 8 bits) := io.axi.w.data(8 * b, 8 bits)
          m(k * cfg.bytePerWord + b) := True
        }
      }
      val flush = io.axi.w.last || lineIndex(next) =/= lineIndex(a)
      out.payload.cmd.data := d
      out.payload.cmd.mask := m
      out.valid := flush
      data := d
      mask := flush ? B(0, Message.Size bits) | m
      addr := next
      busy := !io.axi.w.last
      bursts.ready := io.axi.w.last
    }
    // line writes go out; their answers come back in order; a burst's last answer releases its B
    val (toMem, toTrack) = StreamFork2(outQ, synchronous = true)
    io.write << toMem.translateWith(toMem.cmd).m2sPipe() // registered: the fork's valid waits on both readies
    val track = toTrack.queue(depth)
    io.writeRsp.ready := track.valid
    track.ready := io.writeRsp.fire
    val b = Stream(UInt(cfg.idWidth bits))
    b.valid := io.writeRsp.fire && track.last
    b.payload := track.id
    val bQ = b.queue(depth)
    io.axi.b.valid := bQ.valid
    io.axi.b.id := bQ.payload
    io.axi.b.resp := 0
    bQ.ready := io.axi.b.ready
  }
}

/** The cores' AXI-lite device port: the 16550 and the virtio-mmio slots. Elsewhere reads 0 and
  * ignores writes. */
case class DeviceBridge(slots: Int) extends Component {
  val io = new Bundle {
    val axi = slave(AxiLite4(AxiLite4Config(32, 32)))
    val uart = master(RegBus(3))
    val virtio = master(RegBus(log2Up(slots) + 12))
  }
  val busy = Reg(Bool()) init False
  val isWrite = Reg(Bool())
  val addr = Reg(UInt(32 bits))
  val wdata = Reg(Bits(32 bits))
  val rdata = Reg(Bits(32 bits))
  val respond = Reg(Bool()) init False
  io.axi.aw.ready := !busy && !respond && io.axi.w.valid
  io.axi.w.ready := !busy && !respond && io.axi.aw.valid
  io.axi.ar.ready := !busy && !respond && !(io.axi.aw.valid && io.axi.w.valid)
  when(io.axi.aw.fire) { busy := True; isWrite := True; addr := io.axi.aw.addr; wdata := io.axi.w.data }
  when(io.axi.ar.fire) { busy := True; isWrite := False; addr := io.axi.ar.addr }

  val inUart = addr >= M.Uart && addr < M.Uart + (8 << M.UartRegShift)
  val vOff = addr - M.VirtioBase
  val inVirtio = addr >= M.VirtioBase && addr < M.VirtioBase + slots * M.VirtioStride
  for (b <- Seq(io.uart, io.virtio)) { b.valid := False; b.write := isWrite; b.wdata := wdata }
  io.uart.address := addr(M.UartRegShift + 2 downto M.UartRegShift)
  io.virtio.address := vOff.resized
  when(busy) {
    when(inUart) {
      io.uart.valid := True
      when(io.uart.ready) { rdata := io.uart.rdata; busy := False; respond := True }
    } elsewhen (inVirtio) {
      io.virtio.valid := True
      when(io.virtio.ready) { rdata := io.virtio.rdata; busy := False; respond := True }
    } otherwise { rdata := 0; busy := False; respond := True }
  }
  io.axi.b.valid := respond && isWrite
  io.axi.b.resp := 0
  io.axi.r.valid := respond && !isWrite
  io.axi.r.data := rdata
  io.axi.r.resp := 0
  when(io.axi.b.fire || io.axi.r.fire) { respond := False }
}

case class SocCore(clusterRtl: String, slots: Int = M.VirtioSlots) extends Component {
  val io = new Bundle {
    val rx = slave(Stream(Fragment(Axis64())))
    val tx = master(Stream(Fragment(Axis64())))
    val completerId = in Bits (16 bits)
    val busMaster = in Bool ()
    /** main memory: guest physical line addresses relative to M.Ram */
    val ram = master(Stream(MemCmd()))
    val ramRsp = slave(Stream(Bits(8 * Message.Size bits)))
    val guestReset = out Bool ()
    val ramReady = in Bool ()
    /** the hard block is in reset: the host link starts over (the guest is not touched) */
    val linkReset = in Bool ()
  }
  val link = PcieLink(slots)
  link.io.ramReady := io.ramReady
  link.io.linkReset := io.linkReset
  link.io.rx << io.rx
  io.tx << link.io.tx
  link.io.completerId := io.completerId
  link.io.busMaster := io.busMaster
  io.guestReset := link.io.guestReset

  val cluster = VexiiCluster(clusterRtl)
  cluster.litex_clk := ClockDomain.current.readClockWire
  cluster.litex_reset := ClockDomain.current.isResetActive || link.io.guestReset
  val irqs = Bits(32 bits)
  irqs := 0
  for (s <- 0 until slots) irqs(M.virtioIrq(s)) := link.io.irq(s)
  irqs(M.UartIrq) := link.io.uartIrq
  cluster.peripheral_externalInterrupts_port := irqs

  // the bridges the cores drive are reset with them: a GUEST_RESET in the middle of a burst must not leave
  // a half-finished transaction behind for the next boot
  val guest = new ResetArea(link.io.guestReset, cumulative = true) {
    val devices = DeviceBridge(slots)
    val toLines = Axi4ToLines(SocCore.mBusConfig, M.Ram)
  }
  import guest.{devices, toLines}
  devices.io.axi << cluster.pBus
  link.io.uart <> devices.io.uart
  link.io.guest <> devices.io.virtio

  // main memory: the cores' reads and writes, and the link's boot copies
  toLines.io.axi << cluster.mBus
  val ramArbiter = LineArbiter(3)
  ramArbiter.io.up(0) << toLines.io.read
  toLines.io.readRsp << ramArbiter.io.upRsp(0)
  ramArbiter.io.up(1) << toLines.io.write
  toLines.io.writeRsp << ramArbiter.io.upRsp(1)
  io.ram << ramArbiter.io.down
  ramArbiter.io.downRsp << io.ramRsp

  // the link's memory port: main memory (only reachable through the boot window), or the block RAM
  // behind the DMA and ring windows
  val windows = GuestBram()
  val toRam = link.io.mem.payload.address >= M.Ram && link.io.mem.payload.address < M.Ram + M.RamSize
  val (toMain, toBram) = {
    val d = StreamDemux(link.io.mem, toRam ? U(0) | U(1), 2)
    (d(0), d(1))
  }
  val pendingMain = Reg(Bool()) init False // which one answers the link's single outstanding request
  when(link.io.mem.fire) { pendingMain := toRam }
  ramArbiter.io.up(2) << toMain.translateWith { val c = cloneOf(toMain.payload); c := toMain.payload; c.address.allowOverride; c.address := toMain.payload.address - M.Ram; c }
  windows.io.cmd << toBram
  link.io.memRsp.valid := pendingMain ? ramArbiter.io.upRsp(2).valid | windows.io.rsp.valid
  link.io.memRsp.payload := pendingMain ? ramArbiter.io.upRsp(2).payload | windows.io.rsp.payload
  ramArbiter.io.upRsp(2).ready := pendingMain && link.io.memRsp.ready
  windows.io.rsp.ready := !pendingMain && link.io.memRsp.ready
}
