package card

import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba4.axi._
import spinal.lib.bus.amba4.axilite._
import card.contract.Contract
import Contract.{Message, Map => M}

// S5: the guest's SoC around the host link, in one clock domain. VexiiRiscv's LiteX cluster (generated
// Verilog: cores, CLINT and PLIC at QEMU virt's addresses) reaches main memory through its AXI4 port and
// the devices through its AXI-lite port. Main memory is a port of 64-byte lines that the board's DDR3
// controller serves; the host link's copies share it while GUEST_RESET holds the cores (the boot
// window). The DMA and ring windows are block RAM until S6 puts channel B behind them.

/** VexiiRiscv's LiteX SoC (vexiiriscv.soc.litex.SocGen), generated by designs/soc-s5's prebuild. */
case class VexiiCluster(rtl: String) extends BlackBox {
  setDefinitionName("VexiiCluster")
  val litex_clk = in Bool ()
  val litex_reset = in Bool ()
  val peripheral_externalInterrupts_port = in Bits (32 bits)
  val mBus = master(Axi4(SocCore.mBusConfig))
  val pBus = master(AxiLite4(AxiLite4Config(32, 32)))
  val debug = out Bits (8 bits)
  val mBus_awallStrb = out Bool () // Vexii's hint that a write fills its whole line; unused
  Axi4SpecRenamer(mBus)
  AxiLite4SpecRenamer(pBus)
  addRTLPath(rtl)
}

object SocCore {
  val mBusConfig = Axi4Config(addressWidth = 32, dataWidth = 64, idWidth = 8, useRegion = false, useLock = false,
    useCache = false, useQos = false, useProt = false)
}

/** Requests from several masters onto one line port, one at a time: each request's response goes back to
  * the master that made it. */
case class LineArbiter(n: Int) extends Component {
  val io = new Bundle {
    val up = Vec(slave(Stream(MemCmd())), n)
    val upRsp = Vec(master(Stream(Bits(8 * Message.Size bits))), n)
    val down = master(Stream(MemCmd()))
    val downRsp = slave(Stream(Bits(8 * Message.Size bits)))
  }
  val busy = Reg(Bool()) init False
  val owner = Reg(UInt(log2Up(n) bits)) init 0
  val pick = OHToUInt(OHMasking.first(Vec(io.up.map(_.valid)).asBits)) // the lowest-numbered master first
  io.down.valid := False
  io.down.payload := io.up(pick).payload
  for ((u, i) <- io.up.zipWithIndex) u.ready := !busy && io.down.ready && pick === i
  when(!busy && io.up.map(_.valid).reduce(_ || _)) {
    io.down.valid := True
    when(io.down.ready) { busy := True; owner := pick }
  }
  for ((r, i) <- io.upRsp.zipWithIndex) { r.valid := io.downRsp.valid && busy && owner === i; r.payload := io.downRsp.payload }
  io.downRsp.ready := busy && io.upRsp(owner).ready
  when(io.downRsp.fire) { busy := False }
}

/** The cores' AXI4 memory port as 64-byte line accesses: a read fetches each line its burst touches
  * once; a write gathers the beats of a line into one masked line write. One transaction at a time. */
case class Axi4ToLines(cfg: Axi4Config, base: BigInt) extends Component {
  val io = new Bundle {
    val axi = slave(Axi4(cfg))
    val read = master(Stream(MemCmd()))
    val readRsp = slave(Stream(Bits(8 * Message.Size bits)))
    val write = master(Stream(MemCmd()))
    val writeRsp = slave(Stream(Bits(8 * Message.Size bits)))
  }
  private val lineBits = log2Up(Message.Size)
  private val wordBits = log2Up(cfg.bytePerWord)
  private def lineOf(a: UInt): UInt = (a.resize(64 bits) - base)(63 downto lineBits) @@ U(0, lineBits bits)
  private def sameLine(a: UInt, b: UInt) = a(cfg.addressWidth - 1 downto lineBits) === b(cfg.addressWidth - 1 downto lineBits)

  val rd = new Area {
    val active = Reg(Bool()) init False
    val have = Reg(Bool()) init False // the line holding addr is in buf
    val waiting = Reg(Bool()) init False
    val addr = Reg(UInt(cfg.addressWidth bits))
    val id = Reg(UInt(cfg.idWidth bits))
    val left = Reg(UInt(8 bits))
    val size = Reg(UInt(3 bits))
    val buf = Reg(Bits(8 * Message.Size bits))
    io.axi.ar.ready := !active
    when(io.axi.ar.fire) {
      active := True; have := False; addr := io.axi.ar.addr; id := io.axi.ar.id; left := io.axi.ar.len; size := io.axi.ar.size
    }
    io.read.valid := active && !have && !waiting
    io.read.payload.write := False
    io.read.payload.address := lineOf(addr)
    io.read.payload.data := 0
    io.read.payload.mask := 0
    when(io.read.fire) { waiting := True }
    io.readRsp.ready := True // a response that arrives after a guest reset is dropped, never left blocking the arbiter
    when(io.readRsp.fire && waiting) { buf := io.readRsp.payload; have := True; waiting := False }
    io.axi.r.valid := active && have
    io.axi.r.data := buf.subdivideIn(cfg.dataWidth bits)(addr(lineBits - 1 downto wordBits))
    io.axi.r.id := id
    io.axi.r.resp := 0
    io.axi.r.last := left === 0
    when(io.axi.r.fire) {
      val next = addr + (U(1, cfg.addressWidth bits) |<< size)
      addr := next
      left := left - 1
      when(left === 0) { active := False } elsewhen (!sameLine(addr, next)) { have := False }
    }
  }

  val wr = new Area {
    val active = Reg(Bool()) init False
    val flushing = Reg(Bool()) init False // a gathered line is being written
    val waiting = Reg(Bool()) init False
    val last = Reg(Bool()) init False
    val respond = Reg(Bool()) init False
    val addr = Reg(UInt(cfg.addressWidth bits))
    val line = Reg(UInt(64 bits))
    val id = Reg(UInt(cfg.idWidth bits))
    val size = Reg(UInt(3 bits))
    val data = Reg(Bits(8 * Message.Size bits))
    val mask = Reg(Bits(Message.Size bits)) init 0
    io.axi.aw.ready := !active
    when(io.axi.aw.fire) { active := True; addr := io.axi.aw.addr; id := io.axi.aw.id; size := io.axi.aw.size; mask := 0 }
    io.axi.w.ready := active && !flushing && !respond
    when(io.axi.w.fire) {
      val word = addr(lineBits - 1 downto wordBits)
      val next = addr + (U(1, cfg.addressWidth bits) |<< size)
      for (k <- 0 until Message.Size / cfg.bytePerWord) when(word === k) {
        for (b <- 0 until cfg.bytePerWord) when(io.axi.w.strb(b)) {
          data(8 * (k * cfg.bytePerWord + b), 8 bits) := io.axi.w.data(8 * b, 8 bits)
          mask(k * cfg.bytePerWord + b) := True
        }
      }
      line := lineOf(addr)
      addr := next
      last := io.axi.w.last
      when(io.axi.w.last || !sameLine(addr, next)) { flushing := True }
    }
    io.write.valid := flushing && !waiting
    io.write.payload.write := True
    io.write.payload.address := line
    io.write.payload.data := data
    io.write.payload.mask := mask
    when(io.write.fire) { waiting := True }
    io.writeRsp.ready := True
    when(io.writeRsp.fire && waiting) {
      waiting := False; flushing := False; mask := 0
      when(last) { respond := True }
    }
    io.axi.b.valid := respond
    io.axi.b.id := id
    io.axi.b.resp := 0
    when(io.axi.b.fire) { respond := False; active := False }
  }
}

/** The cores' AXI-lite device port: the 16550 and the virtio-mmio slots. Elsewhere reads 0 and
  * ignores writes. */
case class DeviceBridge(slots: Int) extends Component {
  val io = new Bundle {
    val axi = slave(AxiLite4(AxiLite4Config(32, 32)))
    val uart = master(RegBus(3))
    val virtio = master(RegBus(log2Up(slots) + 12))
  }
  val busy = Reg(Bool()) init False
  val isWrite = Reg(Bool())
  val addr = Reg(UInt(32 bits))
  val wdata = Reg(Bits(32 bits))
  val rdata = Reg(Bits(32 bits))
  val respond = Reg(Bool()) init False
  io.axi.aw.ready := !busy && !respond && io.axi.w.valid
  io.axi.w.ready := !busy && !respond && io.axi.aw.valid
  io.axi.ar.ready := !busy && !respond && !(io.axi.aw.valid && io.axi.w.valid)
  when(io.axi.aw.fire) { busy := True; isWrite := True; addr := io.axi.aw.addr; wdata := io.axi.w.data }
  when(io.axi.ar.fire) { busy := True; isWrite := False; addr := io.axi.ar.addr }

  val inUart = addr >= M.Uart && addr < M.Uart + (8 << M.UartRegShift)
  val vOff = addr - M.VirtioBase
  val inVirtio = addr >= M.VirtioBase && addr < M.VirtioBase + slots * M.VirtioStride
  for (b <- Seq(io.uart, io.virtio)) { b.valid := False; b.write := isWrite; b.wdata := wdata }
  io.uart.address := addr(M.UartRegShift + 2 downto M.UartRegShift)
  io.virtio.address := vOff.resized
  when(busy) {
    when(inUart) {
      io.uart.valid := True
      when(io.uart.ready) { rdata := io.uart.rdata; busy := False; respond := True }
    } elsewhen (inVirtio) {
      io.virtio.valid := True
      when(io.virtio.ready) { rdata := io.virtio.rdata; busy := False; respond := True }
    } otherwise { rdata := 0; busy := False; respond := True }
  }
  io.axi.b.valid := respond && isWrite
  io.axi.b.resp := 0
  io.axi.r.valid := respond && !isWrite
  io.axi.r.data := rdata
  io.axi.r.resp := 0
  when(io.axi.b.fire || io.axi.r.fire) { respond := False }
}

case class SocCore(clusterRtl: String, slots: Int = M.VirtioSlots) extends Component {
  val io = new Bundle {
    val rx = slave(Stream(Fragment(Axis64())))
    val tx = master(Stream(Fragment(Axis64())))
    val completerId = in Bits (16 bits)
    val busMaster = in Bool ()
    /** main memory: guest physical line addresses relative to M.Ram */
    val ram = master(Stream(MemCmd()))
    val ramRsp = slave(Stream(Bits(8 * Message.Size bits)))
    val guestReset = out Bool ()
    val ramReady = in Bool ()
  }
  val link = PcieLink(slots)
  link.io.ramReady := io.ramReady
  link.io.rx << io.rx
  io.tx << link.io.tx
  link.io.completerId := io.completerId
  link.io.busMaster := io.busMaster
  io.guestReset := link.io.guestReset

  val cluster = VexiiCluster(clusterRtl)
  cluster.litex_clk := ClockDomain.current.readClockWire
  cluster.litex_reset := ClockDomain.current.isResetActive || link.io.guestReset
  val irqs = Bits(32 bits)
  irqs := 0
  for (s <- 0 until slots) irqs(M.virtioIrq(s)) := link.io.irq(s)
  irqs(M.UartIrq) := link.io.uartIrq
  cluster.peripheral_externalInterrupts_port := irqs

  // the bridges the cores drive are reset with them: a GUEST_RESET in the middle of a burst must not leave
  // a half-finished transaction behind for the next boot
  val guest = new ResetArea(link.io.guestReset, cumulative = true) {
    val devices = DeviceBridge(slots)
    val toLines = Axi4ToLines(SocCore.mBusConfig, M.Ram)
  }
  import guest.{devices, toLines}
  devices.io.axi << cluster.pBus
  link.io.uart <> devices.io.uart
  link.io.guest <> devices.io.virtio

  // main memory: the cores' reads and writes, and the link's boot copies
  toLines.io.axi << cluster.mBus
  val ramArbiter = LineArbiter(3)
  ramArbiter.io.up(0) << toLines.io.read
  toLines.io.readRsp << ramArbiter.io.upRsp(0)
  ramArbiter.io.up(1) << toLines.io.write
  toLines.io.writeRsp << ramArbiter.io.upRsp(1)
  io.ram << ramArbiter.io.down
  ramArbiter.io.downRsp << io.ramRsp

  // the link's memory port: main memory (only reachable through the boot window), or the block RAM
  // behind the DMA and ring windows
  val windows = GuestBram()
  val toRam = link.io.mem.payload.address >= M.Ram && link.io.mem.payload.address < M.Ram + M.RamSize
  val (toMain, toBram) = {
    val d = StreamDemux(link.io.mem, toRam ? U(0) | U(1), 2)
    (d(0), d(1))
  }
  val pendingMain = Reg(Bool()) init False // which one answers the link's single outstanding request
  when(link.io.mem.fire) { pendingMain := toRam }
  ramArbiter.io.up(2) << toMain.translateWith { val c = cloneOf(toMain.payload); c := toMain.payload; c.address.allowOverride; c.address := toMain.payload.address - M.Ram; c }
  windows.io.cmd << toBram
  link.io.memRsp.valid := pendingMain ? ramArbiter.io.upRsp(2).valid | windows.io.rsp.valid
  link.io.memRsp.payload := pendingMain ? ramArbiter.io.upRsp(2).payload | windows.io.rsp.payload
  ramArbiter.io.upRsp(2).ready := pendingMain && link.io.memRsp.ready
  windows.io.rsp.ready := !pendingMain && link.io.memRsp.ready
}
