set_property LOC AA28 [get_ports SYS_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports SYS_CLK]
set_property LOC P30 [get_ports {led[0]}]
set_property LOC M30 [get_ports {led[1]}]
set_property LOC N30 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property PACKAGE_PIN AH27 [get_ports c0_p]
set_property PACKAGE_PIN AH28 [get_ports c0_n]
set_property PACKAGE_PIN G25 [get_ports c1_p]
set_property PACKAGE_PIN G26 [get_ports c1_n]

set_property IOSTANDARD LVDS_25 [get_ports c0_p]
set_property IOSTANDARD LVDS_25 [get_ports c0_n]
set_property IOSTANDARD LVDS_25 [get_ports c1_p]
set_property IOSTANDARD LVDS_25 [get_ports c1_n]
