#!/usr/bin/env python3
"""The guest SoC's device tree for N harts (SOC-ROADMAP S5: 1, S7: 4): VexiiRiscv RV64IMAFDC harts with Sv39
at 50 MHz, QEMU virt's CLINT and PLIC (a machine and a supervisor context per hart), 2 GiB of DDR3 channel A
at 0x8000_0000, and the console of ../soc/gen/contract-console.dtsi. build-opensbi.sh runs it through cpp
and dtc; OpenSBI embeds the result and hands it to Linux.

  card-dts.py [harts] > card.dts
"""
import sys

harts = int(sys.argv[1]) if len(sys.argv) > 1 else 1
clock = 50_000_000
cpu = """
		cpu{n}: cpu@{n} {{
			device_type = "cpu";
			reg = <{n}>;
			status = "okay";
			compatible = "riscv";
			riscv,isa = "rv64imafdc_zicntr_zicsr_zifencei_zihpm";
			riscv,isa-base = "rv64i";
			riscv,isa-extensions = "i", "m", "a", "f", "d", "c", "zicntr", "zicsr", "zifencei", "zihpm";
			mmu-type = "riscv,sv39";
			clock-frequency = <{clock}>;

			cpu{n}_intc: interrupt-controller {{
				#interrupt-cells = <1>;
				compatible = "riscv,cpu-intc";
				interrupt-controller;
			}};
		}};"""
cpus = "".join(cpu.format(n=n, clock=clock) for n in range(harts))
clint = ", ".join(f"<&cpu{n}_intc 3>, <&cpu{n}_intc 7>" for n in range(harts))   # software, timer (M)
plic = ", ".join(f"<&cpu{n}_intc 11>, <&cpu{n}_intc 9>" for n in range(harts))   # external M, S
print(f"""// Generated by card-dts.py {harts}: the guest SoC with {harts} hart(s). Do not edit.
/dts-v1/;

/ {{
	#address-cells = <2>;
	#size-cells = <2>;
	compatible = "redoubt,ypcb-00338-1p1-soc";
	model = "YPCB-00338-1P1 guest SoC ({harts} hart{'s' if harts > 1 else ''})";

	chosen {{
		bootargs = "console=ttyS0 earlycon=sbi rdinit=/init";
		stdout-path = "serial0";
	}};

	aliases {{
		serial0 = &card_uart;
	}};

	cpus {{
		#address-cells = <1>;
		#size-cells = <0>;
		timebase-frequency = <{clock}>;
{cpus}
	}};

	memory@80000000 {{
		device_type = "memory";
		reg = <0x0 0x80000000 0x0 0x80000000>;
	}};

	soc {{
		#address-cells = <2>;
		#size-cells = <2>;
		compatible = "simple-bus";
		ranges;

		clint@2000000 {{
			compatible = "sifive,clint0", "riscv,clint0";
			reg = <0x0 0x2000000 0x0 0x10000>;
			interrupts-extended = {clint};
		}};

		plic: interrupt-controller@c000000 {{
			compatible = "sifive,plic-1.0.0", "riscv,plic0";
			reg = <0x0 0xc000000 0x0 0x600000>;
			#address-cells = <0>;
			#interrupt-cells = <1>;
			interrupt-controller;
			interrupts-extended = {plic};
			riscv,ndev = <31>;
		}};
	}};
}};

#include "../soc/gen/contract-console.dtsi"

&card_uart {{
	clock-frequency = <{clock}>;
	current-speed = <115200>;
}};""")
